package com.ambianceholidays.api.booking;

import com.ambianceholidays.api.booking.dto.*;
import com.ambianceholidays.common.dto.ApiResponse;
import com.ambianceholidays.domain.agent.AgentRepository;
import com.ambianceholidays.security.SecurityPrincipal;
import jakarta.validation.Valid;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.UUID;

@RestController
@RequestMapping("/cart")
public class CartController {

    private final CartService cartService;
    private final AgentRepository agentRepo;

    public CartController(CartService cartService, AgentRepository agentRepo) {
        this.cartService = cartService;
        this.agentRepo = agentRepo;
    }

    /**
     * Authenticated users: session key = "user:{userId}" (stable across requests).
     * Guests: session key = "guest:{cartId}" where cartId is a UUID generated by the
     * browser and sent in the X-Cart-Id header. Clients must persist this UUID in
     * localStorage and include it on every cart request.
     */
    private String sessionKey(@RequestHeader(value = "X-Cart-Id", required = false) String cartId,
                              SecurityPrincipal principal) {
        if (principal != null) return "user:" + principal.getUserId();
        if (cartId != null && !cartId.isBlank()) return "guest:" + cartId;
        return "guest:anonymous";
    }

    @GetMapping
    public ApiResponse<CartSummaryResponse> getCart(
            @RequestHeader(value = "X-Cart-Id", required = false) String cartId,
            @AuthenticationPrincipal SecurityPrincipal principal) {
        BigDecimal agentMarkup = resolveAgentMarkup(principal);
        return cartService.getCart(sessionKey(cartId, principal), agentMarkup);
    }

    @PostMapping("/items")
    public ApiResponse<CartSummaryResponse> addItem(
            @RequestHeader(value = "X-Cart-Id", required = false) String cartId,
            @AuthenticationPrincipal SecurityPrincipal principal,
            @Valid @RequestBody AddCartItemRequest req) {
        return cartService.addItem(sessionKey(cartId, principal), req);
    }

    @DeleteMapping("/items/{id}")
    public ApiResponse<CartSummaryResponse> removeItem(
            @RequestHeader(value = "X-Cart-Id", required = false) String cartId,
            @AuthenticationPrincipal SecurityPrincipal principal,
            @PathVariable UUID id) {
        return cartService.removeItem(sessionKey(cartId, principal), id);
    }

    @DeleteMapping
    public ApiResponse<Void> clearCart(
            @RequestHeader(value = "X-Cart-Id", required = false) String cartId,
            @AuthenticationPrincipal SecurityPrincipal principal) {
        return cartService.clearCart(sessionKey(cartId, principal));
    }

    private BigDecimal resolveAgentMarkup(SecurityPrincipal principal) {
        if (principal == null) return BigDecimal.ZERO;
        return agentRepo.findByUserIdAndDeletedAtIsNull(principal.getUserId())
                .map(a -> a.getMarkupPercent())
                .orElse(BigDecimal.ZERO);
    }
}
